include ../config.properties
# This CRYPTO_REPO should be the same as repo name in infra variables.tf
CRYPTO_REPO=crypto-base
# chain to pubsub binary
CHAIN_TO_PUBSUB_BIN=ethereumetl

.dummy: prep, init, plan, deploy, undeploy

prep:

init:
 
deploy: 

undeploy: